import type { CargoRow, ContainerSpec, PlanningSettings } from "./types";

export const DEFAULT_CONTAINERS: ContainerSpec[] = [
  {
    type: "20GP",
    category: "STANDARD",
    inner_L_cm: 589,
    inner_W_cm: 235,
    inner_H_cm: 239,
    door_W_cm: 234,
    door_H_cm: 228,
    max_payload_kg: 28_200,
    cost: 7,
    tare_weight_kg: 2_300,
  },
  {
    type: "40GP",
    category: "STANDARD",
    inner_L_cm: 1203,
    inner_W_cm: 235,
    inner_H_cm: 239,
    door_W_cm: 234,
    door_H_cm: 228,
    max_payload_kg: 26_700,
    cost: 6,
    tare_weight_kg: 3_800,
  },
  {
    type: "40HC",
    category: "STANDARD",
    inner_L_cm: 1203,
    inner_W_cm: 235,
    inner_H_cm: 269,
    door_W_cm: 234,
    door_H_cm: 258,
    max_payload_kg: 26_600,
    cost: 6,
    tare_weight_kg: 3_900,
  },
  {
    type: "20OT",
    category: "SPECIAL",
    inner_L_cm: 589,
    inner_W_cm: 235,
    inner_H_cm: 400,
    deck_L_cm: 589,
    deck_W_cm: 235,
    max_payload_kg: 28_200,
    cost: 4,
    tare_weight_kg: 2_300,
  },
  {
    type: "40OT",
    category: "SPECIAL",
    inner_L_cm: 1203,
    inner_W_cm: 235,
    inner_H_cm: 400,
    deck_L_cm: 1203,
    deck_W_cm: 235,
    max_payload_kg: 28_000,
    cost: 3,
    tare_weight_kg: 4_200,
  },
  {
    type: "20FR",
    category: "SPECIAL",
    inner_L_cm: 589,
    inner_W_cm: 240,
    inner_H_cm: 1_000,
    deck_L_cm: 589,
    deck_W_cm: 240,
    max_payload_kg: 30_000,
    cost: 2,
    tare_weight_kg: 2_800,
  },
  {
    type: "40FR",
    category: "SPECIAL",
    inner_L_cm: 1160,
    inner_W_cm: 240,
    inner_H_cm: 1_000,
    deck_L_cm: 1160,
    deck_W_cm: 240,
    max_payload_kg: 34_000,
    cost: 1,
    tare_weight_kg: 5_500,
  },
  {
    type: "RF",
    category: "SPECIAL",
    inner_L_cm: 1150,
    inner_W_cm: 228,
    inner_H_cm: 220,
    door_W_cm: 228,
    door_H_cm: 218,
    max_payload_kg: 27_500,
    cost: 5,
    tare_weight_kg: 4_800,
  },
];

export const DEFAULT_SETTINGS: PlanningSettings = {
  bias_threshold_pct: 20,
  max_cg_offset_x_pct: null,
  max_cg_offset_y_pct: null,
  vehicle_gross_limit_kg: 36_000,
  payload_near_threshold_pct: 90,
  concentration_top_n: 3,
  concentration_warn_threshold_pct: 70,
};

let uidCounter = 0;
export const createUid = () => `cargo-${Date.now()}-${++uidCounter}`;

export const SAMPLE_CARGO: CargoRow[] = [
  {
    uid: "sample-a1001",
    id: "A1001",
    desc: "Steel Coil",
    qty: 2,
    L_cm: 120,
    W_cm: 120,
    H_cm: 90,
    weight_kg: 850,
    package_text: "PALLET",
    rotate_allowed: true,
    stackable: false,
    max_stack_load_kg: null,
    incompatible_with_ids: "",
  },
  {
    uid: "sample-b2001",
    id: "B2001",
    desc: "Carton Boxes",
    qty: 5,
    L_cm: 60,
    W_cm: 40,
    H_cm: 35,
    weight_kg: 18,
    package_text: "CARTON",
    rotate_allowed: true,
    stackable: true,
    max_stack_load_kg: 220,
    incompatible_with_ids: "",
  },
  {
    uid: "sample-c3001",
    id: "C3001",
    desc: "Precision Machine",
    qty: 1,
    L_cm: 210,
    W_cm: 95,
    H_cm: 140,
    weight_kg: 420,
    package_text: "CRATE",
    rotate_allowed: false,
    stackable: false,
    max_stack_load_kg: null,
    incompatible_with_ids: "",
  },
];

export const EMPTY_CARGO = (): CargoRow => ({
  uid: createUid(),
  id: "",
  desc: "",
  qty: 1,
  L_cm: 0,
  W_cm: 0,
  H_cm: 0,
  weight_kg: 0,
  package_text: "",
  rotate_allowed: true,
  stackable: true,
  max_stack_load_kg: null,
  incompatible_with_ids: "",
});

export const CARGO_TEMPLATE_HEADERS = [
  "アイテム番号",
  "貨物名",
  "数量",
  "長さ(cm)",
  "幅(cm)",
  "高さ(cm)",
  "重量(kg)",
  "荷姿",
  "回転可否(TRUE/FALSE)",
  "積み重ね可否(TRUE/FALSE)",
  "上積み許容(kg)",
  "混載不可アイテム番号",
] as const;

export const SAI_M3 = 0.0278;
export const CW_KG_PER_M3 = 166.6667;
export const RT_M3 = 2.83;
export const MT_M3 = 1.1327;
